# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dabest_nb2',
                'doc_host': 'https://ZHANGROU-99.github.io',
                'git_url': 'https://github.com/ZHANGROU-99/dabest_nb2',
                'lib_path': 'dabest_nb2'},
  'syms': {}}
